/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MakeRouteImport } from './routes/make'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as PlayGameIdSplatRouteImport } from './routes/play.$gameId.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdSplatRoute = PlayGameIdSplatRouteImport.update({
  id: '/play/$gameId/$',
  path: '/play/$gameId/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/make': typeof MakeRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/game/$id': typeof GameIdRoute
  '/play/$gameId/$': typeof PlayGameIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/make': typeof MakeRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/game/$id': typeof GameIdRoute
  '/play/$gameId/$': typeof PlayGameIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/make': typeof MakeRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/game/$id': typeof GameIdRoute
  '/play/$gameId/$': typeof PlayGameIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/make'
    | '/search'
    | '/category/$slug'
    | '/game/$id'
    | '/play/$gameId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/make'
    | '/search'
    | '/category/$slug'
    | '/game/$id'
    | '/play/$gameId/$'
  id:
    | '__root__'
    | '/'
    | '/make'
    | '/search'
    | '/category/$slug'
    | '/game/$id'
    | '/play/$gameId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MakeRoute: typeof MakeRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  GameIdRoute: typeof GameIdRoute
  PlayGameIdSplatRoute: typeof PlayGameIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId/$': {
      id: '/play/$gameId/$'
      path: '/play/$gameId/$'
      fullPath: '/play/$gameId/$'
      preLoaderRoute: typeof PlayGameIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MakeRoute: MakeRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  GameIdRoute: GameIdRoute,
  PlayGameIdSplatRoute: PlayGameIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
