/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MakeRouteImport } from './routes/make'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as McpReviewRouteImport } from './routes/mcp_.review'
import { Route as TryTokenRouteImport } from './routes/try.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const McpReviewRoute = McpReviewRouteImport.update({
  id: '/mcp_/review',
  path: '/mcp/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TryTokenRoute = TryTokenRouteImport.update({
  id: '/try/$token',
  path: '/try/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/make': typeof MakeRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/game/$id': typeof GameIdRoute
  '/mcp/review': typeof McpReviewRoute
  '/try/$token': typeof TryTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/make': typeof MakeRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/game/$id': typeof GameIdRoute
  '/mcp/review': typeof McpReviewRoute
  '/try/$token': typeof TryTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/make': typeof MakeRoute
  '/mcp': typeof McpRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/game/$id': typeof GameIdRoute
  '/mcp_/review': typeof McpReviewRoute
  '/try/$token': typeof TryTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/make'
    | '/mcp'
    | '/search'
    | '/category/$slug'
    | '/game/$id'
    | '/mcp/review'
    | '/try/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/make'
    | '/mcp'
    | '/search'
    | '/category/$slug'
    | '/game/$id'
    | '/mcp/review'
    | '/try/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/make'
    | '/mcp'
    | '/search'
    | '/category/$slug'
    | '/game/$id'
    | '/mcp_/review'
    | '/try/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MakeRoute: typeof MakeRoute
  McpRoute: typeof McpRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  GameIdRoute: typeof GameIdRoute
  McpReviewRoute: typeof McpReviewRoute
  TryTokenRoute: typeof TryTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp_/review': {
      id: '/mcp_/review'
      path: '/mcp/review'
      fullPath: '/mcp/review'
      preLoaderRoute: typeof McpReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try/$token': {
      id: '/try/$token'
      path: '/try/$token'
      fullPath: '/try/$token'
      preLoaderRoute: typeof TryTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MakeRoute: MakeRoute,
  McpRoute: McpRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  GameIdRoute: GameIdRoute,
  McpReviewRoute: McpReviewRoute,
  TryTokenRoute: TryTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
