// Hand-authored learning adventures. The generator only packages these designs;
// gameplay lives in the shared runtime/ modules rather than eighty-eight copied engines.
const G = (id, title, emoji, ages, theme, mode, skill, tagline, data = {}) => ({id, title, emoji, ages, theme, mode, skill, tagline, ...data});
export const games = [
G('firefly-lanterns','Firefly Lanterns','✨',[2,4],'forest','collect','One-to-one counting','Light a woodland lantern with just enough fireflies.',{sky:'#263c50',ground:'#4a745c',item:'firefly',noun:'fireflies',verb:'Catch',reward:'The lantern is glowing!'}),
G('orchard-baskets','Orchard Baskets','🍎',[2,5],'orchard','collect','Counting and quantity','Pick a tiny picnic from a candy-coloured orchard.',{item:'apple',noun:'apples',verb:'Pick',reward:'A delicious picnic!'}),
G('moon-pebbles','Moon Pebbles','🌙',[3,6],'space','collect','Counting and stopping at a target','Gather moon gems for a friendly astronaut.',{item:'gem',noun:'moon gems',verb:'Gather',reward:'The moon rover is ready!'}),
G('coral-cleanup','Coral Cleanup','🪸',[3,6],'ocean','collect','Environmental care and classification','Help sea turtles by collecting litter and leaving shells.',{item:'bottle',distractor:'shell',noun:'bottles',verb:'Recycle',reward:'A cleaner reef for everyone!'}),
G('rainbow-postoffice','Rainbow Post Office','📮',[2,4],'village','match','Colour recognition','Deliver rainbow parcels to their matching mailboxes.',{variant:'colour'}),
G('shape-locksmith','Shape Locksmith','🔑',[2,5],'castle','match','Shape recognition','Open a fairy castle with wonderfully shaped keys.',{variant:'shape'}),
G('footprint-detective','Footprint Detective','🐾',[4,7],'forest','match','Observation and animal tracks','Follow curious tracks to their woodland owners.',{variant:'tracks'}),
G('shadow-theatre','Shadow Theatre','🎭',[3,6],'theatre','match','Visual discrimination','Find the toy behind each magical silhouette.',{variant:'shadow'}),
G('habitat-hotel','Habitat Hotel','🏨',[3,7],'village','sort','Animal habitats','Give every animal a room that feels like home.',{bins:['Ocean','Forest','Garden'],items:[['fish','Ocean'],['turtle','Ocean'],['fox','Forest'],['bear','Forest'],['bee','Garden'],['butterfly','Garden']]}),
G('recycling-robots','Recycling Robots','♻️',[4,8],'workshop','sort','Materials and recycling','Sort toy recyclables with a cheerful robot team.',{bins:['Paper','Glass','Metal'],items:[['📦','Paper'],['📰','Paper'],['🍾','Glass'],['🫙','Glass'],['🥫','Metal'],['🥄','Metal']]}),
G('fruit-veggie-ferry','Fruit & Veggie Ferry','⛵',[3,6],'harbour','sort','Food classification','Load two tiny ferries for a healthy island picnic.',{bins:['Fruit','Vegetables'],items:[['apple','Fruit'],['pear','Fruit'],['strawberry','Fruit'],['carrot','Vegetables'],['🥦','Vegetables'],['🥬','Vegetables']]}),
G('season-suitcase','Season Suitcase','🧳',[4,7],'village','sort','Seasons and weather','Pack sunny-day and snowy-day adventures.',{bins:['Warm day','Cold day'],items:[['🧤','Cold day'],['🧣','Cold day'],['🧥','Cold day'],['🩴','Warm day'],['🕶️','Warm day'],['👒','Warm day']]}),
G('butterfly-patterns','Butterfly Patterns','🦋',[3,6],'garden','pattern','Repeating colour patterns','Grow a dancing line of patterned butterfly wings.',{tokens:['🦋','🌸','🌿'],kind:'repeat'}),
G('bead-bridge','Bead Bridge','📿',[3,7],'castle','pattern','AB, AAB and ABC sequences','Finish a jewel bridge for the royal snail.',{tokens:['🔴','🔵','🟡'],kind:'repeat'}),
G('train-carriage-rhythm','Train Carriage Rhythm','🚂',[4,7],'railway','pattern','Pattern prediction','Complete the toy train’s changing carriage pattern.',{tokens:['🚃','📦','🌳'],kind:'repeat'}),
G('constellation-code','Constellation Code','🌌',[5,8],'space','pattern','Number sequences','Repair a star map by finding the missing number.',{kind:'number'}),
G('sprout-sunflower','Sprout to Sunflower','🌻',[3,6],'garden','order','Plant life cycle','Help a seed tell the story of how it grows.',{stages:['🌰 Seed','🌱 Sprout','🌿 Leaves','🌻 Flower'],fact:'Plants use light and water to grow.',
  lifeModels:['sunflowerseed','sprout','leaf','sunflower'],
  stageFacts:['A seed holds the beginnings of a plant.','A sprout grows roots and a shoot.','Leaves collect light.','The sunflower blooms and can make new seeds.'],
}),
G('breakfast-story','Breakfast Story','🥣',[3,6],'bakery','order','Everyday sequencing','Put a bear’s cosy morning in a sensible order.',{stages:['🛏️ Wake up','🧼 Wash hands','🥣 Eat breakfast','🪥 Brush teeth'],fact:'Washing hands before eating helps keep us healthy.',
  lifeModels:['bed','washstand','bowl','toothbrush'],
  stageFacts:['The bear wakes up.','Wash hands before eating.','Breakfast gives the bear energy.','Brush teeth to care for them.'],
}),
G('frog-life-lab','Frog Life Lab','🐸',[4,8],'pond','order','Frog metamorphosis','Watch pond eggs grow into a hopping frog.',{stages:['🥚 Eggs','🐟 Tadpole','🦵 Tadpole with legs','🐸 Frog'],fact:'A tadpole grows legs as it becomes a frog.',
  lifeModels:['frogspawn','tadpole','froglet','frog'],
  stageFacts:['Frog eggs hatch in water.','A tadpole swims with a tail.','The tadpole grows legs.','The young frog’s tail shrinks.'],
}),
G('butterfly-life-lab','Butterfly Life Lab','🐛',[4,8],'garden','order','Butterfly metamorphosis','Unfold a caterpillar’s remarkable transformation.',{stages:['🥚 Egg','🐛 Caterpillar','🟤 Chrysalis','🦋 Butterfly'],fact:'A butterfly changes inside its chrysalis.',
  lifeModels:['leafeggs','caterpillar','chrysalis','butterfly'],
  stageFacts:['A butterfly lays eggs on a plant.','A caterpillar hatches and eats leaves.','Inside the chrysalis, the body changes.','The butterfly emerges and its wings expand.'],
}),
G('dinosaur-size-parade','Dinosaur Size Parade','🦕',[2,5],'prehistoric','compare','Relative size','Find the tiny and towering friends in a dinosaur parade.',{variant:'size',item:'dino'}),
G('cloud-number-race','Cloud Number Race','☁️',[4,7],'sky','compare','Comparing numbers','Choose the bigger or smaller number on floating clouds.',{variant:'number'}),
G('ribbon-tailor','Ribbon Tailor','🎀',[3,6],'theatre','compare','Length comparison','Choose just the right ribbon for a toy costume.',{variant:'length'}),
G('deep-sea-divers','Deep Sea Divers','🤿',[4,7],'ocean','compare','Spatial vocabulary and depth','Spot the diver nearest the surface or deepest in the sea.',{variant:'depth',item:'fish'}),
G('picnic-pairs','Picnic Pairs','🧺',[2,5],'orchard','memory','Visual working memory','Uncover matching snacks beneath picnic blankets.',{pairs:[['🍎','🍎'],['🍐','🍐'],['🍓','🍓'],['🥕','🥕'],['🍋','🍋'],['🍇','🍇']]}),
G('planet-pairs','Planet Pairs','🪐',[3,7],'space','memory','Visual memory','Remember where the little space souvenirs are hiding.',{pairs:[['Mercury','Mercury'],['Venus','Venus'],['Earth','Earth'],['Mars','Mars'],['Jupiter','Jupiter'],['Saturn','Saturn']]}),
G('tool-twins','Tool Twins','🛠️',[4,8],'workshop','memory','Jobs and their tools','Pair a helper with the tool they use.',{pairs:[['🧑‍🍳','🥣'],['🧑‍🌾','🌱'],['🧑‍🎨','🖌️'],['🧑‍🚒','🚒'],['🧑‍🔧','🔧'],['🧑‍✈️','✈️']]}),
G('letter-buddies','Letter Buddies','🔤',[4,7],'library','memory','Uppercase and lowercase letters','Introduce big letters to their little-letter buddies.',{pairs:[['A','a'],['B','b'],['D','d'],['E','e'],['M','m'],['R','r']]}),
G('frog-choir','Frog Choir','🎶',[3,7],'pond','echo','Auditory and sequential memory','Echo a pond chorus on colourful lily pads.',{tokens:['🐸','🌸','🐟','🍃'],notes:[262,330,392,523]}),
G('crystal-cave-echo','Crystal Cave Echo','💎',[4,8],'cave','echo','Pitch and sound sequence memory','Remember the sparkling song of a crystal cave.',{tokens:['💜','💙','💚','💛'],notes:[294,370,440,587]}),
G('robot-dance-code','Robot Dance Code','🤖',[4,8],'workshop','echo','Following ordered instructions','Teach a toy robot a dance one move at a time.',{tokens:['⬆️','➡️','⬇️','⬅️'],notes:[220,277,330,440]}),
G('sleepy-owl-lullaby','Sleepy Owl Lullaby','🦉',[2,5],'forest','echo','Short sequence recall','Repeat a gentle bedtime song for a sleepy owl.',{night:true,sky:'#34364f',ground:'#7a8b79',tokens:['🌙','⭐','☁️'],notes:[262,330,392]}),
G('bee-pollen-trail','Bee Pollen Trail','🐝',[4,7],'garden','path','Route planning and pollination','Guide a bee around stones to a waiting flower.',{hero:'bee',goal:'flower',obstacle:'stone'}),
G('turtle-treasure-map','Turtle Treasure Map','🐢',[4,8],'harbour','path','Grid navigation','Steer a turtle through a reef to a secret pearl.',{hero:'turtle',goal:'shell',obstacle:'stone'}),
G('rover-rescue','Rover Rescue','🛸',[5,8],'space','path','Algorithms and obstacle avoidance','Program a moon rover to rescue a stranded rocket.',{hero:'robot',goal:'rocket',obstacle:'gem'}),
G('penguin-ice-path','Penguin Ice Path','🐧',[4,7],'arctic','path','Direction and planning','Lead a penguin across safe ice to a fish picnic.',{hero:'penguin',goal:'fish',obstacle:'stone'}),
G('snail-spiral','Snail Spiral','🐌',[2,5],'garden','trace','Fine motor control and curves','Follow a glimmering spiral to the snail’s flower.',{trace:'spiral',hero:'snail'}),
G('kite-flight-school','Kite Flight School','🪁',[3,6],'sky','trace','Hand-eye coordination','Draw swooping sky trails for a rainbow kite.',{trace:'wave',hero:'kite'}),
G('letter-trails','Letter Trails','✏️',[4,7],'library','trace','Letter formation','Trace large glowing letters with a friendly firefly.',{trace:'letter',hero:'firefly'}),
G('number-spark-trails','Number Spark Trails','🔢',[4,7],'space','trace','Numeral formation','Draw sparkling numerals across a moon garden.',{trace:'number',hero:'star'}),
G('acorn-addition','Acorn Addition','🐿️',[4,8],'forest','arithmetic','Concrete addition','Combine two acorn stashes for a woodland feast.',{operation:'add',item:'acorn'}),
G('submarine-subtraction','Submarine Subtraction','🐠',[5,8],'ocean','arithmetic','Concrete subtraction','See how many fish remain after friends swim away.',{operation:'subtract',item:'fish'}),
G('bakery-bundles','Bakery Bundles','🥐',[5,8],'bakery','arithmetic','Equal groups and multiplication','Count buns arranged in equal bakery trays.',{operation:'multiply',item:'bread'}),
G('star-share','Star Share','⭐',[5,8],'space','arithmetic','Fair sharing and division','Share star biscuits equally between space explorers.',{operation:'divide',item:'star'}),
G('bear-balance','Bear Balance','⚖️',[4,7],'forest','balance','Equality and weights','Balance a bear’s seesaw with numbered acorns.',{unit:'acorns',item:'acorn'}),
G('parcel-weights','Parcel Weights','📦',[5,8],'village','balance','Missing addends','Find the parcel that balances a delivery scale.',{unit:'weight units',item:'parcel'}),
G('pebble-equations','Pebble Equations','🪨',[5,8],'pond','balance','Number decomposition','Build equal pebble piles on a pond seesaw.',{unit:'pebbles',item:'stone'}),
G('colour-cauldron','Colour Cauldron','🧙',[3,6],'castle','mix','Primary and secondary colours','Brew bright new colours in a friendly witch’s pot.',{vessel:'cauldron'}),
G('rainbow-smoothies','Rainbow Smoothies','🥤',[3,6],'bakery','mix','Colour mixing','Mix two pretend fruit colours into a rainbow smoothie.',{vessel:'smoothie'}),
G('jellyfish-glow-lab','Jellyfish Glow Lab','🪼',[4,7],'ocean','mix','Predicting colour combinations','Blend paint colours for a glowing jellyfish costume.',{vessel:'jellyfish'}),
G('paint-a-planet','Paint a Planet','🎨',[3,7],'space','mix','Colour experimentation','Mix a paint colour for a tiny new planet.',{vessel:'planet'}),
G('pizza-moon','Pizza Moon','🍕',[5,8],'bakery','fraction','Equal parts and fractions','Share moon-shaped pizzas in equal slices.',{food:'pizza',symbol:'🍕'}),
G('watermelon-picnic','Watermelon Picnic','🍉',[5,8],'orchard','fraction','Part-whole reasoning','Colour equal slices of a picnic watermelon.',{food:'watermelon',symbol:'🍉'}),
G('rainbow-quilt','Rainbow Quilt','🧵',[5,8],'theatre','fraction','Fractions of a collection','Sew the right fraction of patches into a quilt.',{food:'quilt',symbol:'🟪'}),
G('cuckoo-clock-garden','Cuckoo Clock Garden','🕰️',[5,8],'garden','clock','Telling time','Turn the clock hands for a tiny garden concert.',{event:'The birds sing at'}),
G('space-station-schedule','Space Station Schedule','🛰️',[6,8],'space','clock','Hours and half hours','Set a station clock for the next rocket launch.',{event:'The rocket leaves at'}),
G('bunny-bedtime','Bunny Bedtime','🐰',[5,8],'village','clock','Clock reading and daily routines','Set a cosy clock for bunny’s daily routine.',{event:'Bunny reads a story at'}),
G('bakery-alarm','Bakery Alarm','⏰',[5,8],'bakery','clock','Hours and quarter hours','Set the kitchen clock for a pretend bake.',{event:'The bread is ready at'}),
G('butterfly-mirrors','Butterfly Mirrors','🪞',[4,8],'garden','mirror','Reflection symmetry','Give a butterfly two beautifully matching wings.',{subject:'butterfly wings'}),
G('castle-window-symmetry','Castle Window Symmetry','🏰',[5,8],'castle','mirror','Grid reflection','Restore mirrored jewel panes in a fairy castle.',{subject:'castle windows'}),
G('robot-reflections','Robot Reflections','🤖',[5,8],'workshop','mirror','Spatial reasoning','Light both halves of a robot’s panel symmetrically.',{subject:'robot lights'}),
G('snowflake-studio','Snowflake Studio','❄️',[4,8],'arctic','mirror','Symmetrical patterns','Copy a glittering snowflake across its mirror line.',{subject:'snowflake crystals'}),
G('gem-turner','Gem Turner','🔷',[4,7],'cave','rotate','Mental rotation','Turn a crystal key until it fits the glowing lock.',{subject:'crystal key',shape:'triangle'}),
G('rocket-docking','Rocket Docking','🚀',[5,8],'space','rotate','Rotation and direction','Turn a rocket’s docking key into the correct position.',{subject:'docking key',shape:'arrow'}),
G('tangram-turntable','Tangram Turntable','🔺',[4,8],'theatre','rotate','Tangram composition and rotation','Fit five triangles, a square, and a parallelogram into a complete tangram.',{subject:'triangle',shape:'triangle'}),
G('giraffe-ruler','Giraffe Ruler','🦒',[4,7],'prehistoric','measure','Measuring with equal units','Measure a toy giraffe with colourful cube units.',{subject:'giraffe’s height',unit:'cubes'}),
G('bridge-builder','Bridge Builder','🌉',[4,8],'harbour','measure','Length and unit iteration','Lay equal planks across a little harbour gap.',{subject:'bridge',unit:'planks'}),
G('garden-fence','Garden Fence','🌷',[4,7],'garden','measure','Length estimation','Measure a flower bed before making its tiny fence.',{subject:'flower bed',unit:'fence pieces'}),
G('comet-tail-measure','Comet Tail Measure','☄️',[5,8],'space','measure','Measuring with consistent units','Measure sparkling comet tails without gaps.',{subject:'comet tail',unit:'star units'}),
G('word-rocket','Word Rocket','🔠',[5,8],'space','spell','CVC word building','Build short words to power a reading rocket.',{words:[['CAT','🐱'],['SUN','☀️'],['DOG','🐶'],['HAT','🎩'],['MAP','🗺️'],['CUP','☕']]}),
G('animal-alphabet','Animal Alphabet','🦊',[4,7],'forest','spell','Beginning sounds and spelling','Build names for tiny animal friends.',{words:[['FOX','🦊','fox'],['CAT','🐱','cat'],['PIG','🐷','pig'],['HEN','🐔','hen'],['BAT','🦇','bat'],['DOG','🐶','dog']],
  // No scenery fox: the only animal on the island is the one being spelled. The fox greets on the menu and win card.
  scenery:['tree','mushroom','acorn','flower'],hero:'fox'}),
G('picnic-word-basket','Picnic Word Basket','🧺',[5,8],'orchard','spell','Food word spelling','Pack a picnic by spelling simple snack words.',{words:[['JAM','🫙'],['EGG','🥚'],['NUT','🌰'],['BUN','🥯'],['PEA','🫛'],['HAM','🍖']]}),
G('rhyming-river','Rhyming River','📖',[5,8],'pond','rhyme','Rhyming word families','Hop between lily pads with words that rhyme.',{sets:[['CAT','HAT','DOG','SUN'],['LOG','DOG','HEN','CUP'],['BEE','TREE','CAT','MAP'],['FOX','BOX','SUN','PIG'],['STAR','CAR','BED','HEN'],['BOAT','GOAT','FISH','CAT']]}),
G('weather-wardrobe','Weather Wardrobe','🌦️',[3,6],'village','choice','Weather and practical reasoning','Dress a toy explorer for sun, rain, and snow.',{challenges:[['🌧️ Rain! What keeps us dry?','☂️ Umbrella','🕶️ Sunglasses','🩴 Sandals'],['❄️ Snow! What keeps hands warm?','🧤 Mittens','🪭 Fan','🩴 Sandals'],['☀️ Sunshine! What shades our head?','👒 Sun hat','🧣 Scarf','🛷 Sled'],['🌧️ Puddles! What keeps feet dry?','🥾 Rain boots','🩴 Sandals','🧦 Socks']],storyToys:['umbrella','gloves','hat','boots','glasses','sandal','scarf']}),
G('kindness-cafe','Kindness Café','💛',[3,7],'bakery','choice','Empathy and cooperation','Choose caring actions at a tiny toy café.',{
  challenges:[
    ['Bear is sad. What could you ask?',['Would you like company?','Would you like quiet time?'],'Let me give advice first'],
    ['Bunny needs a cup now. What could help?',['Offer a spare cup','Ask where clean cups are'],'Finish my drink first'],
    ['Fox spills juice. What could help?',['Help clean together','Offer a cloth'],'Tell fox to be more careful'],
    ['Turtle is waiting to play. What is kind?',['Agree to take turns','Ask to play together'],'Start another game alone'],
  ],
  storyToys:['bear','rabbit','fox','turtle','cup'],
}),
G('healthy-plate-party','Healthy Plate Party','🥗',[4,7],'orchard','choice','Food variety and healthy routines','Help toy friends choose varied snacks and routines.',{
  challenges:[
    ['What is a good everyday drink?',['💧 Water','🥛 Milk'],'🍬 Sweets'],
    ['What adds a vegetable to lunch?','🥦 Broccoli','🍞 Bread','🧀 Cheese'],
    ['What do we do before eating?','👐 Wash hands','🥤 Fill a cup','🪑 Choose a seat'],
    ['What adds a fruit to our snack?','🍐 Pear','🥨 Pretzel','🧀 Cheese'],
  ],
  storyToys:['broccoli','pear','bread','cup'],
}),
G('senses-safari','Senses Safari','👂',[3,6],'forest','choice','The five senses','Discover how our senses help us explore.',{challenges:[['🎵 Which body part hears music?','👂 Ears','👀 Eyes','👃 Nose'],['🌸 Which body part smells flowers?','👃 Nose','👂 Ears','🦶 Feet'],['🌈 Which body part sees colours?','👀 Eyes','👃 Nose','👂 Ears'],['🧸 How can we feel a soft toy?','🖐️ Touch','👀 Look only','👂 Listen only'],['🍋 Which body part tastes lemon?','👅 Tongue','👂 Ears','👃 Nose']],storyToys:['drum','flower','butterfly','teddy','lemon']}),
G('magnet-discovery','Magnet Discovery','🧲',[5,8],'workshop','experiment','Testing magnetic attraction','Predict, test, and discover what a magnet attracts.',{property:'magnet',sets:[['🔩 Steel screw',true,'screw'],['📎 Steel paperclip',true,'paperclip'],['🪵 Wood',false,'wood'],['🍎 Apple',false,'apple'],['🧲 Iron nail',true,'nail'],['🧸 Cloth teddy',false,'teddy']]}),
G('float-boat-lab','Float Boat Lab','🛁',[4,8],'harbour','experiment','Prediction and buoyancy','Test toy objects in a tiny water tank.',{property:'float',sets:[['🪵 Dry wood',true,'wood'],['🪨 Stone',false,'stone'],['🦆 Hollow rubber duck',true,'duck'],['🔩 Solid steel screw',false,'screw'],['🧽 Dry sponge',true,'sponge'],['🫙 Solid glass marble',false,'marble']]}),
G('sunlight-sprouts','Sunlight Sprouts','🌱',[4,7],'garden','experiment','Plants and their needs','Discover which supplies help a garden grow.',{property:'grow',sets:[['💧 Water',true,'bottle'],['☀️ Sunlight',true,'sun'],['🍬 Sweets',false,'candy'],['🪨 A toy rock',false,'stone'],['🌱 Suitable soil',true,'soil'],['🎨 Paint',false,'paint']]}),
G('sound-wave-lab','Sound Wave Lab','🔔',[4,8],'cave','pitch','Pitch discrimination','Compare crystal tones and find the high or low sound.',{subject:'crystals'}),
G('birdsong-tuner','Birdsong Tuner','🐦',[3,7],'garden','pitch','High and low sounds','Listen closely to tune a miniature birdsong concert.',{subject:'birds'}),
G('drum-beat-builder','Drum Beat Builder','🥁',[4,8],'theatre','rhythm','Rhythmic patterns','Rebuild a drum pattern using beats and quiet rests.',{subject:'drum'}),
G('rain-drop-rhythm','Rain Drop Rhythm','🌧️',[3,7],'pond','rhythm','Beat, rests and pattern memory','Copy a gentle rain song on a lily-pad drum.',{subject:'rain'}),
G('toy-town-builder','Toy Town Builder','🏘️',[4,8],'village','build','Spatial construction from plans','Build a miniature skyline from a block blueprint.',{subject:'town'}),
G('castle-block-blueprints','Castle Block Blueprints','🏯',[4,8],'castle','build','Height and spatial reasoning','Raise little castle towers to match the royal plan.',{subject:'castle'}),
G('dino-egg-nest','Dino Egg Nest','🥚',[2,5],'prehistoric','tenframe','Subitising and number representation','Fill a dino’s nest with the right number of eggs.',{item:'egg',noun:'eggs'}),
G('ladybird-dot-party','Ladybird Dot Party','🐞',[3,6],'garden','tenframe','Ten-frame counting','Add dots to a ladybird’s ten little garden seats.',{item:'gem',noun:'dots'}),
];
const sortingProps={
  '📦':{model:'parcel',label:'Cardboard box'},
  '📰':{model:'newspaper',label:'Newspaper'},
  '🍾':{model:'bottle',label:'Glass bottle'},
  '🫙':{model:'jar',label:'Glass jar'},
  '🥫':{model:'can',label:'Metal can'},
  '🥄':{model:'spoon',label:'Metal spoon'},
  '🥦':{model:'broccoli',label:'Broccoli'},
  '🥬':{model:'cabbage',label:'Cabbage'},
  '🧤':{model:'gloves',label:'Gloves'},
  '🧣':{model:'scarf',label:'Scarf'},
  '🧥':{model:'coat',label:'Winter coat'},
  '🩴':{model:'sandal',label:'Sandal'},
  '🕶️':{model:'glasses',label:'Sunglasses'},
  '👒':{model:'hat',label:'Sun hat'},
};
// Sorting games show labelled 3D props for the emoji items that have a model.
for(const g of games.filter(g=>g.mode==='sort')){
  g.props=Object.fromEntries(g.items.filter(([item])=>sortingProps[item]).map(([item])=>[item,sortingProps[item]]));
}
if (games.length !== 88) throw new Error(`Expected 88 new games, found ${games.length}`);
export const themes = {
 forest: ['#dcebd6','#4e8060','#f2b36f',['tree','mushroom','acorn','fox']],
 orchard: ['#ffe5cf','#b8d58b','#ef796e',['tree','apple','pear','basket']],
 space: ['#282955','#7c7bbb','#ffd179',['planet','rocket','gem','star']],
 ocean: ['#d3f3f5','#79ced2','#ffb0bc',['coral','shell','fish','turtle']],
 village: ['#e9dff7','#b6a7d3','#f2b572',['house','tree','parcel','flower']],
 castle: ['#f4dcef','#c6a7d1','#ffd786',['castle','flower','gem','tree']],
 theatre: ['#f9d9dc','#d19bae','#fbc985',['star','drum','kite','gem']],
 garden: ['#e4f4df','#9ccd9c','#f7a8c3',['flower','mushroom','butterfly','snail']],
 harbour: ['#daedf8','#7dbbd3','#f6c784',['boat','house','shell','tree']],
 railway: ['#fbe8d3','#a4c4b0','#efae72',['train','tree','house','parcel']],
 prehistoric: ['#efe9cf','#adbb85','#e7aa74',['dino','tree','egg','stone']],
 sky: ['#dfeefa','#a9c9e4','#f6bfd7',['cloud','kite','star','bird']],
 library: ['#f6e7d1','#c3aa92','#e5a077',['house','tree','book','bear']],
 workshop: ['#e0ebed','#99bfc3','#f8c974',['robot','house','gear','parcel']],
 pond: ['#e0efd9','#91c4ad','#f5c17c',['leaf','flower','frog','snail']],
 cave: ['#e2dff6','#a59acb','#80ded5',['gem','stone','mushroom','star']],
 arctic: ['#e3effb','#a6cfe2','#edbedc',['penguin','stone','fish','cloud']],
 bakery: ['#f9e1cc','#d4ac8a','#f3a8aa',['bread','house','strawberry','bear']],
};
export const instructions = {
 collect:'Tap the requested number of objects, then press Done. Tap again to undo.',
 match:'Look at the delivery request and tap its matching toy.',
 sort:'Carry objects to their homes, or tap an object and then its home.',
 pattern:'Look for the repeating rule. Tap the piece that fills the empty place.',
 order:'Tap the pictures in the order the story happens. Use Reset to start again.',
 compare:'Listen to the request. Compare the objects and tap your answer.',
 memory:'Turn over two cards. Match their pictures or their related meanings.',
 echo:'Watch and listen to the song, then tap the pads in the same order. Replay whenever you like.',
 path:'Use the arrow buttons to plan a route. Press Go to send your friend. Avoid the rocks.',
 trace:'Start at the glowing dot. Hold and follow the trail, or tap each dot in order.',
 arithmetic:'Move the toys to tell the story. Make equal shares when sharing, then choose an answer.',
 balance:'Choose weights for the empty pan until both sides are equal. Press Check.',
 mix:'Tap two primary paint colours to make the target colour. Reset to try another blend.',
 fraction:'Tap equal parts to colour the requested share. Press Check when ready.',
 clock:'Turn the hour and minute hands using the buttons. Match the requested time, then Check.',
 mirror:'Tap squares on the empty side to reflect the pattern across the dotted line. Press Check.',
 rotate:'Turn the colourful key in quarter turns until it matches the pale outline. Press Check.',
 measure:'Place equal units along the glowing length without gaps. Press Check.',
 spell:'Look at the picture and listen to the word. Tap its letters in order.',
 rhyme:'Listen to the word. Pick a word with the same ending sound.',
 choice:'Listen to the little story, then choose the helpful answer.',
 experiment:'Make a prediction, press Test, and see what happens. Try both ideas.',
 pitch:'Play both sounds, then choose the higher or lower one. Replay as often as you like.',
 rhythm:'Listen to the rhythm. Set each step to a beat or a rest, then play your pattern.',
 build:'Tap the towers to add blocks. Match the heights in the blueprint, then Check.',
 tenframe:'Tap the ten little spaces to fill the requested number. Press Check.',
};
